name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Print API Token (For Testing Only)
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: echo "Token saat ini adalah $API_TOKEN"  
