name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Secret Variable
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Using API Token: $API_TOKEN"
          # Contoh penggunaan API Token dalam skrip
          curl -X GET https://api.example.com/data -H "Authorization: Bearer $API_TOKEN"
